language: go

go:
  - 1.5
  - 1.6

before_install:
  - go get golang.org/x/lint/golint

install:
  - go install -race -v std
  - go get -race -t ./...
  - go install -race -v ./...

script:
  - $HOME/gopath/bin/golint .
  - make test
